### ISSUE TITLE
Is k-means Iterator not iterate at all?

### ISSUE THREAD

**Issue by yancanmao** [0x7aF777/StreamBench#9]
I viewed the source code, and found it didn't have the feature you write in paper...I think Compute centroid didn't update data to Initialized centroid. `UserFunctions.pointMapToPair` didn't receive updated centroid, and `UserFunctions.computeCentroid` didn't send updated centroid either. Maybe I'm wrong...

`WorkloadOperator<Point> centroids = assigned_points
                    .mapToPair(UserFunctions.pointMapToPair, "mapToPair")
                    .reduceByKey(UserFunctions.pointAggregator, "aggregator")
                    .map(UserFunctions.computeCentroid, "centroid", Point.class);`
![image](https://user-images.githubusercontent.com/24371733/35211882-363fb8f0-ff93-11e7-852d-74d328a8d1f2.png)

**Comment by 0x7aF777** [comment]
Hello, the main point of `iterator` here is the `closeWith` method. Except the `closeWith` part, other parts is a chain of steps to process points and get the updated centroid. The `closeWith` put updated `centroids` back to the point steam which also contains normal points. There is a `isCentroid` method of `Point` class to check whether a point is a centroid.

**Comment by yancanmao** [comment]
Oh, I see , really thank you for answer my question:)

**Comment by 0x7aF777** [comment]
Sorry for my late reply
